/// <reference types="vite/client" />

// Format-variant imports generated by vite-imagetools return a URL string.
declare module "*?format=avif&w=720&quality=55" {
  const src: string;
  export default src;
}
declare module "*?format=webp&w=720&quality=68" {
  const src: string;
  export default src;
}
declare module "*?format=avif&w=1600&quality=52" {
  const src: string;
  export default src;
}
declare module "*?format=webp&w=1600&quality=65" {
  const src: string;
  export default src;
}
declare module "*?format=avif" {
  const src: string;
  export default src;
}
declare module "*?format=webp" {
  const src: string;
  export default src;
}
