/// <reference types="vite/client" />

// Format-variant imports generated by vite-imagetools return a URL string.
declare module "*?format=avif" {
  const src: string;
  export default src;
}
declare module "*?format=webp" {
  const src: string;
  export default src;
}
